    alter table annotation 
        drop constraint FKA34FEB2F2E6479A;

    alter table annotation_proposal 
        drop constraint FKB41BD602DD7ABCF2;

    alter table annotation_proposal 
        drop constraint FKB41BD6026CD5827A;

    alter table darwin_core 
        drop constraint FK7CDBC4B79450E664;

    alter table darwin_core 
        drop constraint FK7CDBC4B786115B5A;

    alter table darwin_core 
        drop constraint FK7CDBC4B7F4A31FEE;

    alter table extension_mapping 
        drop constraint FKC5F42CCE50C7406B;

    alter table extension_mapping 
        drop constraint FKC5F42CCE9450E664;

    alter table extension_mapping 
        drop constraint FKC5F42CCEE6B2BACE;

    alter table extension_property 
        drop constraint FKB1C849D57C086588;

    alter table extension_property 
        drop constraint FKB1C849D5E6B2BACE;

    alter table occ_stat_by_region_and_taxon 
        drop constraint FK18B7A4842E6479A;

    alter table occ_stat_by_region_and_taxon 
        drop constraint FK18B7A48486115B5A;

    alter table occ_stat_by_region_and_taxon 
        drop constraint FK18B7A484F4A31FEE;

    alter table property_mapping 
        drop constraint FKD70CF8645010B26D;

    alter table property_mapping 
        drop constraint FKD70CF864EA81FC27;

    alter table property_mapping 
        drop constraint FKD70CF864A2643235;

    alter table region 
        drop constraint FKC84826F4FD0995E4;

    alter table region 
        drop constraint FKC84826F49450E664;

    alter table resource 
        drop constraint FKEBABC40E4FFFD4FE;

    alter table resource 
        drop constraint FKEBABC40E497AF9C2;

    alter table resource 
        drop constraint FKEBABC40EA1C4CE73;

    alter table resource_keywords 
        drop constraint FKBFE8BCBB2E6479A;

    alter table resource_services 
        drop constraint FKF2EF2D6F2E6479A;

    alter table source_base 
        drop constraint FKFAEC30759450E664;

    alter table taxon 
        drop constraint FK6908ECA7FAFDA0E;

    alter table taxon 
        drop constraint FK6908ECA9450E664;

    alter table taxon 
        drop constraint FK6908ECAB110B664;

    alter table taxon 
        drop constraint FK6908ECAAF70C6D7;

    alter table term_mapping 
        drop constraint FKE30CD7FB53D0913A;

    alter table thesaurus_concept 
        drop constraint FK51A890237C086588;

    alter table thesaurus_term 
        drop constraint FKB5D48091FCFE7D00;

    alter table transformation 
        drop constraint FK9C65130950C7406B;

    alter table transformation 
        drop constraint FK9C6513099450E664;

    alter table transformation 
        drop constraint FK9C651309A7BC3324;

    alter table upload_event 
        drop constraint FKAF0A9EDC2E6479A;

    alter table user_role 
        drop constraint FK143BF46AF503D155;

    alter table user_role 
        drop constraint FK143BF46A4FD90D75;

    drop table annotation if exists;

    drop table annotation_proposal if exists;

    drop table app_user if exists;

    drop table darwin_core if exists;

    drop table extension if exists;

    drop table extension_mapping if exists;

    drop table extension_property if exists;

    drop table occ_stat_by_region_and_taxon if exists;

    drop table property_mapping if exists;

    drop table provider_cfg if exists;

    drop table region if exists;

    drop table resource if exists;

    drop table resource_keywords if exists;

    drop table resource_services if exists;

    drop table role if exists;

    drop table source_base if exists;

    drop table taxon if exists;

    drop table term_mapping if exists;

    drop table thesaurus_concept if exists;

    drop table thesaurus_term if exists;

    drop table thesaurus_vocabulary if exists;

    drop table transformation if exists;

    drop table upload_event if exists;

    drop table user_role if exists;

    create table annotation (
        id bigint generated by default as identity,
        created timestamp,
        creator varchar(64),
        guid varchar(128),
        note clob,
        probability integer,
        remove_during_import bit not null,
        source_id varchar(128),
        type varchar(32) not null,
        resource_fk bigint not null,
        primary key (id)
    );

    create table annotation_proposal (
        annotation_fk bigint not null,
        proposal_element varchar(255),
        proposal_mapkey_fk bigint not null,
        primary key (annotation_fk, proposal_mapkey_fk)
    );

    create table app_user (
        id bigint generated by default as identity,
        account_expired bit not null,
        account_locked bit not null,
        address_address varchar(150),
        address_city varchar(50),
        address_country varchar(100),
        postal_code varchar(15),
        address_province varchar(100),
        credentials_expired bit not null,
        email varchar(255) not null unique,
        account_enabled bit,
        first_name varchar(50) not null,
        last_name varchar(50) not null,
        password varchar(255) not null,
        password_hint varchar(255),
        phone_number varchar(255),
        username varchar(50) not null unique,
        version integer,
        website varchar(255),
        primary key (id)
    );

CREATE TABLE darwin_core (
id bigint generated by default as identity,
deleted bit not null,
guid varchar(128) not null unique,
link varchar(255),
source_id varchar(64),
lat double,
lon double,
region_fk bigint,
taxon_fk bigint,
resource_fk bigint not null,
type varchar(32),
modified timestamp,
language varchar(64),
rights clob,
rightsHolder varchar(255),
accessRights clob,
bibliographicCitation varchar(255),
institutionID varchar(255),
collectionID varchar(255),
datasetID varchar(255),
institutionCode varchar(128),
collectionCode varchar(64),
datasetName varchar(255),
ownerInstitutionCode varchar(128),
basisOfRecord varchar(64),
informationWithheld clob,
dataGeneralizations clob,
dynamicProperties clob,
occurrenceID varchar(255),
catalogNumber varchar(64),
occurrenceDetails clob,
occurrenceRemarks clob,
recordNumber varchar(64),
recordedBy varchar(255),
individualID varchar(255),
individualCount varchar(64),
sex varchar(128),
lifeStage varchar(128),
reproductiveCondition varchar(255),
behavior varchar(255),
establishmentMeans varchar(255),
occurrenceStatus varchar(255),
preparations varchar(255),
disposition varchar(128),
otherCatalogNumbers varchar(255),
previousIdentifications clob,
associatedMedia clob,
associatedReferences clob,
associatedOccurrences clob,
associatedSequences clob,
associatedTaxa clob,
eventID varchar(255),
samplingProtocol clob,
samplingEffort varchar(255),
eventDate varchar(64),
eventTime varchar(32),
startDayOfYear varchar(16),
endDayOfYear varchar(16),
year varchar(16),
month varchar(16),
day varchar(16),
verbatimEventDate varchar(255),
habitat varchar(255),
fieldNumber varchar(255),
fieldNotes clob,
eventRemarks clob,
locationID varchar(255),
higherGeographyID varchar(255),
higherGeography varchar(255),
continent varchar(128),
waterBody varchar(255),
islandGroup varchar(255),
island varchar(255),
country varchar(128),
countryCode varchar(32),
stateProvince varchar(255),
county varchar(255),
municipality varchar(255),
locality clob,
verbatimLocality clob,
verbatimElevation varchar(255),
minimumElevationInMeters varchar(32),
maximumElevationInMeters varchar(32),
verbatimDepth varchar(255),
minimumDepthInMeters varchar(32),
maximumDepthInMeters varchar(32),
minimumDistanceAboveSurfaceInMeters varchar(32),
maximumDistanceAboveSurfaceInMeters varchar(32),
locationAccordingTo varchar(255),
locationRemarks clob,
verbatimCoordinates varchar(255),
verbatimLatitude varchar(128),
verbatimLongitude varchar(128),
verbatimCoordinateSystem varchar(255),
verbatimSRS varchar(255),
decimalLatitude varchar(32),
decimalLongitude varchar(32),
geodeticDatum varchar(255),
coordinateUncertaintyInMeters varchar(32),
coordinatePrecision varchar(64),
pointRadiusSpatialFit varchar(64),
footprintWKT clob,
footprintSRS varchar(255),
footprintSpatialFit varchar(128),
georeferencedBy varchar(255),
georeferenceProtocol varchar(255),
georeferenceSources clob,
georeferenceVerificationStatus varchar(128),
georeferenceRemarks clob,
geologicalContextID varchar(255),
earliestEonOrLowestEonothem varchar(255),
latestEonOrHighestEonothem varchar(255),
earliestEraOrLowestErathem varchar(255),
latestEraOrHighestErathem varchar(255),
earliestPeriodOrLowestSystem varchar(255),
latestPeriodOrHighestSystem varchar(255),
earliestEpochOrLowestSeries varchar(255),
latestEpochOrHighestSeries varchar(255),
earliestAgeOrLowestStage varchar(255),
latestAgeOrHighestStage varchar(255),
lowestBiostratigraphicZone varchar(255),
highestBiostratigraphicZone varchar(255),
lithostratigraphicTerms varchar(255),
grouppp varchar(255),
formation varchar(255),
member varchar(255),
bed varchar(255),
identificationID varchar(255),
identifiedBy varchar(255),
dateIdentified varchar(64),
identificationReferences clob,
identificationRemarks clob,
identificationQualifier varchar(255),
typeStatus varchar(255),
taxonID varchar(255),
scientificNameID varchar(255),
acceptedNameUsageID varchar(255),
parentNameUsageID varchar(255),
originalNameUsageID varchar(255),
nameAccordingToID varchar(255),
namePublishedInID varchar(255),
taxonConceptID varchar(255),
scientificName varchar(255),
acceptedNameUsage varchar(255),
parentNameUsage varchar(255),
originalNameUsage varchar(255),
nameAccordingTo varchar(255),
namePublishedIn varchar(255),
higherClassification varchar(255),
kingdom varchar(128),
phylum varchar(255),
classs varchar(255),
orderrr varchar(255),
family varchar(255),
genus varchar(255),
subgenus varchar(255),
specificEpithet varchar(255),
infraspecificEpithet varchar(255),
taxonRank varchar(128),
verbatimTaxonRank varchar(255),
scientificNameAuthorship varchar(255),
vernacularName varchar(255),
nomenclaturalCode varchar(64),
taxonomicStatus varchar(128),
nomenclaturalStatus varchar(128),
taxonRemarks clob,
primary key (id),
unique (source_id, resource_fk)
);


    create table extension (
        id bigint generated by default as identity,
        installed bit not null,
        link varchar(255),
        namespace varchar(128),
        title varchar(128),
        name varchar(64),
        core bit not null,
        modified timestamp,
        primary key (id)
    );

    create table extension_mapping (
        id bigint generated by default as identity,
        localid_col varchar(128),
        link_col varchar(128),
        link_template varchar(255),
        rec_total integer not null,
        extension_fk bigint,
        source_fk bigint,
        resource_fk bigint not null,
        primary key (id)
    );

    create table extension_property (
        id bigint generated by default as identity,
        column_length integer not null,
        link varchar(255),
        name varchar(64),
        namespace varchar(128),
        required bit not null,
        extension_fk bigint not null,
        property_order integer not null,
        vocabulary_fk bigint,
        groupp varchar(64),
        primary key (id)
    );

    create table occ_stat_by_region_and_taxon (
        id bigint generated by default as identity,
        bbox_max_latitude double,
        bbox_max_longitude double,
        bbox_min_latitude double,
        bbox_min_longitude double,
        num_occ integer not null,
        taxon_fk bigint,
        resource_fk bigint not null,
        region_fk bigint,
        primary key (id)
    );

    create table property_mapping (
        id bigint generated by default as identity,
        column varchar(255),
        value varchar(255),
        view_mapping_fk bigint not null,
        property_fk bigint,
        term_transformation_fk bigint,
        primary key (id)
    );

    create table provider_cfg (
        id bigint generated by default as identity,
        base_url varchar(128),
        description_image varchar(255),
        gbif_analytics bit not null,
        geoserver_data_dir varchar(128),
        geoserver_pass varchar(64),
        geoserver_url varchar(128),
        geoserver_user varchar(64),
        google_maps_api_key varchar(128),
        header_html clob,
        ipt_meta_contact_email varchar(64),
        ipt_meta_contact_name varchar(128),
        ipt_meta_description clob,
        ipt_meta_link varchar(255),
        ipt_meta_location_latitude double,
        ipt_meta_location_longitude double,
        ipt_meta_title varchar(128),
        ipt_meta_uddi_id varchar(64) unique,
        log4j_filename varchar(64),
        org_meta_contact_email varchar(64),
        org_meta_contact_name varchar(128),
        org_meta_description clob,
        org_meta_link varchar(255),
        org_meta_location_latitude double,
        org_meta_location_longitude double,
        org_meta_title varchar(128),
        org_meta_uddi_id varchar(64) unique,
        org_node varchar(128),
        org_password varchar(128),
        primary key (id)
    );

    create table region (
        id bigint generated by default as identity,
        bbox_max_latitude double,
        bbox_max_longitude double,
        bbox_min_latitude double,
        bbox_min_longitude double,
        label varchar(255),
        lft bigint,
        mpath varchar(255),
        occ_total integer not null,
        rgt bigint,
        type integer,
        resource_fk bigint not null,
        parent_fk bigint,
        primary key (id)
    );

    create table resource (
        dtype varchar(31) not null,
        id bigint generated by default as identity,
        created timestamp,
        geo_coverage_max_latitude double,
        geo_coverage_max_longitude double,
        geo_coverage_min_latitude double,
        geo_coverage_min_longitude double,
        guid varchar(128) not null unique,
        meta_contact_email varchar(64),
        meta_contact_name varchar(128),
        meta_description clob,
        meta_link varchar(255),
        meta_location_latitude double,
        meta_location_longitude double,
        meta_title varchar(128),
        meta_uddi_id varchar(64) unique,
        modified timestamp,
        status integer,
        type varchar(64),
        jdbc_driver_class varchar(64),
        jdbc_password varchar(64),
        jdbc_url varchar(128),
        jdbc_user varchar(64),
        num_accepted integer,
        num_classes integer,
        num_families integer,
        num_genera integer,
        num_kingdoms integer,
        num_orders integer,
        num_phyla integer,
        num_species integer,
        num_synonyms integer,
        num_taxa integer,
        num_terminal_taxa integer,
        num_common_name_languages integer,
        num_common_names integer,
        num_distribution_regions integer,
        num_distributions integer,
        bbox_max_latitude double,
        bbox_max_longitude double,
        bbox_min_latitude double,
        bbox_min_longitude double,
        feature_hash integer,
        num_countries integer,
        num_regions integer,
        num_terminal_regions integer,
        rec_with_altitude integer,
        rec_with_coordinates integer,
        rec_with_country integer,
        rec_with_date integer,
        modifier_fk bigint,
        creator_fk bigint,
        last_upload_event_fk bigint,
        primary key (id)
    );

    create table resource_keywords (
        resource_fk bigint not null,
        keywords_element varchar(255)
    );

    create table resource_services (
        resource_fk bigint not null,
        services_element varchar(255),
        services_mapkey varchar(255),
        primary key (resource_fk, services_mapkey)
    );

    create table role (
        id bigint generated by default as identity,
        description varchar(64),
        name varchar(20),
        primary key (id)
    );

    create table source_base (
        dtype varchar(31) not null,
        id bigint generated by default as identity,
        name varchar(128) not null,
        sql clob,
        headers bit,
        resource_fk bigint not null,
        primary key (id)
    );

    create table taxon (
        id bigint generated by default as identity,
        bbox_max_latitude double,
        bbox_max_longitude double,
        bbox_min_latitude double,
        bbox_min_longitude double,
        label varchar(255),
        lft bigint,
        mpath varchar(255),
        occ_total integer not null,
        rgt bigint,
        type integer,
        deleted bit not null,
        guid varchar(128) not null unique,
        infraspecific_epithet varchar(128),
        link varchar(255),
        modified timestamp,

        nameAccordingToID varchar(255),
        nameAccordingTo varchar(255),
        namePublishedInID varchar(255),
        namePublishedIn varchar(255),
        nomenclaturalCode varchar(64),
        nomenclaturalStatus varchar(128),
        scientificNameAuthorship varchar(255),
        scientificNameID varchar(255),
        source_id varchar(64),
        specificEpithet varchar(255),
        taxonConceptID varchar(255),
        taxonRank varchar(128),
        taxonRemarks clob,
        taxonomicStatus varchar(128),
        verbatimTaxonRank varchar(255),
        vernacularName varchar(255),
        bas_fk bigint,
        acc_fk bigint,
        parent_fk bigint,
        resource_fk bigint not null,
        primary key (id),
        unique (source_id, resource_fk)
    );

    create table term_mapping (
        id bigint generated by default as identity,
        target_term varchar(128),
        term varchar(255),
        transformation_fk bigint not null,
        primary key (id)
    );

    create table thesaurus_concept (
        id bigint generated by default as identity,
        uri varchar(255),
        issued timestamp,
        identifier varchar(64),
        vocabulary_fk bigint not null,
        concept_order integer,
        link varchar(255),
        primary key (id)
    );

    create table thesaurus_term (
        id bigint generated by default as identity,
        preferred bit not null,
        created timestamp,
        lang varchar(8),
        modified timestamp,
        relation varchar(255),
        source varchar(128),
        title varchar(255),
        concept_fk bigint not null,
        primary key (id)
    );

    create table thesaurus_vocabulary (
        id bigint generated by default as identity,
        modified timestamp,
        title varchar(255),
        uri varchar(255),
        link varchar(255),
        primary key (id)
    );

    create table transformation (
        id bigint generated by default as identity,
        column varchar(255),
        type integer,
        resource_fk bigint not null,
        voc_fk bigint,
        source_fk bigint not null,
        primary key (id)
    );

    create table upload_event (
        id bigint generated by default as identity,
        execution_date timestamp,
        job_source_id integer not null,
        job_source_type integer not null,
        records_added integer not null,
        records_changed integer not null,
        records_deleted integer not null,
        records_erroneous integer not null,
        records_uploaded integer not null,
        resource_fk bigint not null,
        duration bigint not null,
        eml_version integer not null,
        primary key (id)
    );

    create table user_role (
        user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    create index annotation_guid on annotation (guid);

    alter table annotation 
        add constraint FKA34FEB2F2E6479A 
        foreign key (resource_fk) 
        references resource;

    alter table annotation_proposal 
        add constraint FKB41BD602DD7ABCF2 
        foreign key (proposal_mapkey_fk) 
        references extension_property;

    alter table annotation_proposal 
        add constraint FKB41BD6026CD5827A 
        foreign key (annotation_fk) 
        references annotation;

    create index deleted on darwin_core (deleted);

    create index longitude on darwin_core (lon);

    create index idx_dwc_country on darwin_core (country);

    create index dwc_date_collected on darwin_core (eventDate);

    create index dwc_source_id on darwin_core (source_id);

    create index idx_dwc_institution_code on darwin_core (institutionCode);

    create index idx_dwc_catalog_number on darwin_core (catalogNumber);

    create index idx_dwc_basis_of_record on darwin_core (basisOfRecord);

    create index guid on darwin_core (guid);

    create index latitude on darwin_core (lat);

    create index idx_dwc_collection_code on darwin_core (collectionCode);

    create index idx_dwc_scientific_name on darwin_core (scientificName);

    alter table darwin_core 
        add constraint FK7CDBC4B79450E664 
        foreign key (resource_fk) 
        references resource;

    alter table darwin_core 
        add constraint FK7CDBC4B786115B5A 
        foreign key (region_fk) 
        references region;

    alter table darwin_core 
        add constraint FK7CDBC4B7F4A31FEE 
        foreign key (taxon_fk) 
        references taxon;

    alter table extension_mapping 
        add constraint FKC5F42CCE50C7406B 
        foreign key (source_fk) 
        references source_base;

    alter table extension_mapping 
        add constraint FKC5F42CCE9450E664 
        foreign key (resource_fk) 
        references resource;

    alter table extension_mapping 
        add constraint FKC5F42CCEE6B2BACE 
        foreign key (extension_fk) 
        references extension;

    create index idx_extension_property_name on extension_property (name);

    create index idx_extension_property_ns on extension_property (namespace);

    create index idx_extension_property_group on extension_property (groupp);

    alter table extension_property 
        add constraint FKB1C849D57C086588 
        foreign key (vocabulary_fk) 
        references thesaurus_vocabulary;

    alter table extension_property 
        add constraint FKB1C849D5E6B2BACE 
        foreign key (extension_fk) 
        references extension;

    alter table occ_stat_by_region_and_taxon 
        add constraint FK18B7A4842E6479A 
        foreign key (resource_fk) 
        references resource;

    alter table occ_stat_by_region_and_taxon 
        add constraint FK18B7A48486115B5A 
        foreign key (region_fk) 
        references region;

    alter table occ_stat_by_region_and_taxon 
        add constraint FK18B7A484F4A31FEE 
        foreign key (taxon_fk) 
        references taxon;

    alter table property_mapping 
        add constraint FKD70CF8645010B26D 
        foreign key (property_fk) 
        references extension_property;

    alter table property_mapping 
        add constraint FKD70CF864EA81FC27 
        foreign key (term_transformation_fk) 
        references transformation;

    alter table property_mapping 
        add constraint FKD70CF864A2643235 
        foreign key (view_mapping_fk) 
        references extension_mapping;

    create index title on provider_cfg (ipt_meta_title, org_meta_title);

    create index reg_lft on region (lft);

    create index reg_rgt on region (rgt);

    create index reg_label on region (label);

    alter table region 
        add constraint FKC84826F4FD0995E4 
        foreign key (parent_fk) 
        references region;

    alter table region 
        add constraint FKC84826F49450E664 
        foreign key (resource_fk) 
        references resource;

    create index resource_title on resource (meta_title);

    alter table resource 
        add constraint FKEBABC40E4FFFD4FE 
        foreign key (creator_fk) 
        references app_user;

    alter table resource 
        add constraint FKEBABC40E497AF9C2 
        foreign key (last_upload_event_fk) 
        references upload_event;

    alter table resource 
        add constraint FKEBABC40EA1C4CE73 
        foreign key (modifier_fk) 
        references app_user;

    alter table resource_keywords 
        add constraint FKBFE8BCBB2E6479A 
        foreign key (resource_fk) 
        references resource;

    alter table resource_services 
        add constraint FKF2EF2D6F2E6479A 
        foreign key (resource_fk) 
        references resource;

    alter table source_base 
        add constraint FKFAEC30759450E664 
        foreign key (resource_fk) 
        references resource;

    create index tax_lft on taxon (lft);

    create index tax_label on taxon (label);

    create index tax_source_id on taxon (source_id);

    create index tax_rgt on taxon (rgt);

    create index tax_deleted on taxon (deleted);

    create index tax_guid on taxon (guid);

    alter table taxon 
        add constraint FK6908ECA7FAFDA0E 
        foreign key (parent_fk) 
        references taxon;

    alter table taxon 
        add constraint FK6908ECA9450E664 
        foreign key (resource_fk) 
        references resource;

    alter table taxon 
        add constraint FK6908ECAB110B664 
        foreign key (bas_fk) 
        references taxon;

    alter table taxon 
        add constraint FK6908ECAAF70C6D7 
        foreign key (acc_fk) 
        references taxon;

    alter table term_mapping 
        add constraint FKE30CD7FB53D0913A 
        foreign key (transformation_fk) 
        references transformation;

    create index concept_uri on thesaurus_concept (uri);

    create index concept_identifier on thesaurus_concept (identifier);

    alter table thesaurus_concept 
        add constraint FK51A890237C086588 
        foreign key (vocabulary_fk) 
        references thesaurus_vocabulary 
        on delete cascade;

    create index term_title on thesaurus_term (title);

    alter table thesaurus_term 
        add constraint FKB5D48091FCFE7D00 
        foreign key (concept_fk) 
        references thesaurus_concept;

    alter table transformation 
        add constraint FK9C65130950C7406B 
        foreign key (source_fk) 
        references source_base;

    alter table transformation 
        add constraint FK9C6513099450E664 
        foreign key (resource_fk) 
        references resource;

    alter table transformation 
        add constraint FK9C651309A7BC3324 
        foreign key (voc_fk) 
        references thesaurus_vocabulary;

    alter table upload_event 
        add constraint FKAF0A9EDC2E6479A 
        foreign key (resource_fk) 
        references resource;

    alter table user_role 
        add constraint FK143BF46AF503D155 
        foreign key (user_id) 
        references app_user;

    alter table user_role 
        add constraint FK143BF46A4FD90D75 
        foreign key (role_id) 
        references role;
