https://builds.gbif.org/job/ipt/lastBuild/console[image:https://builds.gbif.org/job/ipt/badge/icon[Build status]]

= GBIF Integrated Publishing Toolkit (IPT)

The Integrated Publishing Toolkit (IPT) is a free, open source software tool used to publish and share biodiversity datasets through the https://www.gbif.org/[GBIF network]. The IPT can also be configured with a DataCite account in order to assign DOIs to datasets, thus transforming it into a data repository.

In this repository you can find the IPT source code, https://ipt.gbif.org/manual/[IPT User Manual] source code, and the https://github.com/gbif/ipt/issues[IPT issue tracker].

****
*Most users should refer to the https://ipt.gbif.org/manual/[user manual] for further information.*
****

== Resources

* https://ipt.gbif.org/manual/[IPT User Manual]
* Information on the https://ipt.gbif.org/manual/en/ipt/2.5/releases/[latest release] and the https://ipt.gbif.org/manual/en/ipt/2.5/news/#next-release[next release]
* The https://ipt.gbif.org[Demo IPT] is available online, https://ipt.gbif.org/manual/en/ipt/2.5/getting-started/[further information about this]
* You may request a free account on an IPT from a https://ipt.gbif.org/manual/en/ipt/2.5/data-hosting-centres/[trusted data hosting centre]
* How to contribute https://ipt.gbif.org/manual/en/ipt/2.5/translations/[translations] with https://crowdin.com/project/gbif-ipt[Crowdin]
* https://lists.gbif.org/mailman/listinfo/ipt/[IPT Mailing List] — please subscribe for notifications of future releases.

== Acknowledgements

A large number of dedicated volunteers contribute to the success of this software. With your help, the IPT has become a successful tool in use all around the world.

https://crowdin.com/[Crowdin] is kindly supporting this https://crowdin.com/project/gbif-ipt[open source project] by giving GBIF a free access to its localization management platform. Crowdin makes it possible to manage a large number of concurrent translations.
