https://builds.gbif.org/job/ipt/lastBuild/console[image:https://builds.gbif.org/job/ipt/badge/icon[Build status]]
https://crowdin.com/project/gbif-ipt[image:https://badges.crowdin.net/gbif-ipt/localized.svg[Crowdin]]

= GBIF Integrated Publishing Toolkit (IPT)

The Integrated Publishing Toolkit (IPT) is a free, open source software tool provided by the Global Biodiversity Information Facility (GBIF) and used to publish and share biodiversity datasets through the https://www.gbif.org/[GBIF network]. The IPT can also be configured with a DataCite account in order to assign DOIs to datasets, thus transforming it into a data repository.

[TIP]
====
*Most users should refer to the https://ipt.gbif.org/manual/[user manual] for further information, including https://ipt.gbif.org/manual/en/ipt/latest/releases[downloads], https://ipt.gbif.org/manual/en/ipt/latest/getting-started[installation instructions] and details of the https://ipt.gbif.org/manual/en/ipt/latest/releases[latest release].*

If you have a GitHub account, you may select "Watch" → "Custom" → "Releases" above to receive
a notification from GitHub when there is a new IPT release. These notifications are also sent to the https://lists.gbif.org/mailman/listinfo/ipt/[mailing list].
====

In this repository you can find the source code for the IPT software and its https://ipt.gbif.org/manual/[user manual], as well as the https://github.com/gbif/ipt/issues[issue tracker].

== Resources

* https://ipt.gbif.org/manual/[IPT User Manual]
* Information on the https://ipt.gbif.org/manual/en/ipt/latest/releases[latest release]
* The https://ipt.gbif.org[Demo IPT] is available online, https://ipt.gbif.org/manual/en/ipt/latest/getting-started[further information about this]
* How to contribute https://ipt.gbif.org/manual/en/ipt/latest/translations[translations] with https://crowdin.com/project/gbif-ipt[Crowdin]
* https://lists.gbif.org/mailman/listinfo/ipt/[IPT Mailing List] — please subscribe for notifications of future releases.

== Acknowledgements

A large number of dedicated volunteers contribute to the success of this software. With your help, the IPT has become a successful tool in use all around the world.

https://crowdin.com/[Crowdin] is kindly supporting this https://crowdin.com/project/gbif-ipt[open source project] by giving GBIF a free access to its localization management platform. Crowdin makes it possible to manage a large number of concurrent translations.
