package org.gbif.provider.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * A mapping between a single extension property (concept) and a resource represented via the viewMapping.
 * A mapping can either be a fixed value (String) or the column index of the resultset generated by the viewMapping sql statement.
 * @author markus
 *
 */
@Entity
public class PropertyMapping {
	private Long id;	
	private ViewMapping viewMapping;
	private ExtensionProperty property;
	private String value;
	private Integer column;
	
	@Id @GeneratedValue(strategy = GenerationType.AUTO) 
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(optional=false)
	public ViewMapping getViewMapping() {
		return viewMapping;
	}
	public void setViewMapping(ViewMapping viewMapping) {
		this.viewMapping = viewMapping;
	}
	
	@ManyToOne(optional=false)
	public ExtensionProperty getProperty() {
		return property;
	}
	public void setProperty(ExtensionProperty property) {
		this.property = property;
	}
	
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	
	@Column(name="column_index")
	public Integer getColumn() {
		return column;
	}
	public void setColumn(Integer column) {
		this.column = column;
	}
	
	
}
