= GBIF Integrated Publishing Toolkit 2.0.4: Release Notes

include::partial$version-outdated.adoc[]

== Upgrade instructions

. Performing the upgrade
+
--
WARNING: It is always a good idea to take the precaution of backing up the existing IPT data directory before performing an upgrade.

An upgrade can be performed in 3 steps:

. Replace the previous .war file with the latest edition
. Backup the existing data directory
. Reuse the existing data directory during setup
--

. Post-upgrade instructions
+
--
Once the upgrade is complete, resource managers should:

. Reset the resource subtype (if applicable), making the selection on the basic metadata page. The reason being that this list now refers to a controlled vocabulary in IPT 2.0.4 and previous selections will have been reset.
. Re-save the metadata for each resource. The reason being that additional validation has been added to the metadata pages in IPT 2.0.4 in order to ensure better compliance with the GBIF metadata profile.
--

. Other
+
The style/CSS in IPT 2.0.4 has been revised. The unfortunate outcome is that all customization guides written for earlier versions of the IPT are no longer applicable. GBIF hopes to release an updated customization guide for IPT 2.0.4 shortly after release.

== Dependency Notes

This new version has been tested and designed to work on Tomcat 6.0 or 7.0.
Please note IPT 2.0.4 is still designed to run on Java 5 and later.

== Viewing the IPT change log

This version addressed a total of 108 issues: 38 Defects, 35 Enhancements, 7 Other, 5 Patches, 18 Won't fix, 4 Duplicates, and 1 that was considered as Invalid.

These are detailed in the issue tracking system:
http://code.google.com/p/gbif-providertoolkit/issues/list?can=1&q=milestone%3DRelease2.0.4

== When all else fails

See the FAQ:
http://code.google.com/p/gbif-providertoolkit/wiki/FAQ
