= GBIF Integrated Publishing Toolkit 2.0.3: Release Notes

include::partial$version-outdated-page-removed.adoc[]

== Upgrade instructions

To upgrade from an earlier version of the IPT, this version requires the Administrator to press the  "Publish all resources" button on the Administration page immediately after specifying the location of the existing IPT data directory and pressing the "continue" button.

It is always a good idea to take the precaution of backing up the existing IPT data directory before performing an upgrade.

== Dependency Notes

This new version is known to work on Tomcat 7.0, whereas problems were reported using this version of Tomcat for IPT 2.0.2. Please note IPT 2.0.3 is still designed to run on Java 5 and later.

== Viewing the IPT change log

This version addressed 76 issues (43 defects, 33 enhancements/patches)
See http://code.google.com/p/gbif-providertoolkit/issues/list?can=1&q=milestone%3DRelease2.0.3

== When all else fails

See the FAQ http://code.google.com/p/gbif-providertoolkit/wiki/FAQ
