= 版本歷史

[TIP]
.Latest stable release
====
The current, stable release is version <<3-1-3-january-2025,3.1.3>>.

ifeval::["{language}" != "en"]
You are reading the latest version of the manual. You can read older versions of the manual using the selectors at the top-right or bottom-left of the screen. Note that the not all manual versions are available in TRANSLATOR_PUT_YOUR_LANGUAGE_HERE.
endif::[]
====

== *3.1.3* – January 2025

* https://repository.gbif.org/content/groups/gbif/org/gbif/ipt/3.1.3/ipt-3.1.3.war[Download WAR], xref:installation.adoc#installation-from-linux-packages[Linux packages] or xref:installation.adoc#installation-from-docker[use Docker]
* xref:release-notes.adoc[IPT v3.1.3 Release Notes]
* xref:index.adoc[User Manual]
* Addressed https://github.com/gbif/ipt/milestone/64?closed=1[7 issues].
* Translated into 7 languages

This minor release includes bug fixes for Camtrap DP and some small improvements.

Existing users should upgrade to this version following the instructions in the xref:release-notes.adoc[Release Notes]. New users should follow the xref:getting-started.adoc[Getting Started guide].

No release date has been set for the next release. Progress working on issues for the next release can be browsed https://github.com/gbif/ipt/milestones[on GitHub].

Minor issues and security issues will be addressed in patch releases.

== *3.1.2* – December 2024

* https://repository.gbif.org/content/groups/gbif/org/gbif/ipt/3.1.2/ipt-3.1.2.war[Download WAR], xref:installation.adoc#installation-from-linux-packages[Linux packages] or xref:installation.adoc#installation-from-docker[use Docker]
* xref:release-notes.adoc[IPT v3.1.2 Release Notes]
* xref:index.adoc[User Manual]
* Addressed https://github.com/gbif/ipt/milestone/63?closed=1[20 issues].
* Translated into 7 languages

This minor release brings support to ColDP. Also, it introduces some general improvements and bug fixes with source creation and file upload.

== *3.1.1* – December 2024

* https://repository.gbif.org/content/groups/gbif/org/gbif/ipt/3.1.1/ipt-3.1.1.war[Download WAR], xref:installation.adoc#installation-from-linux-packages[Linux packages] or xref:installation.adoc#installation-from-docker[use Docker]
* xref:release-notes.adoc[IPT v3.1.1 Release Notes]
* xref:index.adoc[User Manual]
* Addressed https://github.com/gbif/ipt/milestone/62?closed=1[7 issues].
* Translated into 7 languages

This minor release introduces some general improvements and addresses issues with mappings to some extensions.

== *3.1.0* – October 2024

* https://repository.gbif.org/content/groups/gbif/org/gbif/ipt/3.1.0/ipt-3.1.0.war[Download WAR], xref:installation.adoc#installation-from-linux-packages[Linux packages] or xref:installation.adoc#installation-from-docker[use Docker]
* xref:release-notes.adoc[IPT v3.1.0 Release Notes]
* xref:index.adoc[User Manual]
* Addressed https://github.com/gbif/ipt/milestone/60?closed=1[48 issues].
* Translated into 7 languages

This major release introduces support for EML 2.2.0.

== *3.0.6* – June 2024

* Addressed https://github.com/gbif/ipt/milestone/58?closed=1[3 issues].
* Translated into 7 languages

This minor release addresses issues with taxonomic metadata description and registry network warnings.

== *3.0.5* – June 2024

* Addressed https://github.com/gbif/ipt/milestone/57?closed=1[5 issues].
* Translated into 7 languages

This minor release addresses issues with vocabulary update, Camtrap resource registration, and more.

== *3.0.4* – May 2024

* Addressed https://github.com/gbif/ipt/milestone/56?closed=1[2 issues].
* Translated into 7 languages

This minor release addresses issues with metadata.

== *3.0.3* – April 2024

* Addressed https://github.com/gbif/ipt/milestone/55?closed=1[4 issues].
* Translated into 7 languages

This minor release addresses issues with metadata and DOI issuing.

== *3.0.2* – April 2024

* Addressed https://github.com/gbif/ipt/milestone/54?closed=1[11 issues].
* Translated into 7 languages

This minor release addresses issues with inferred metadata, DOI functionality, and setup.

== *3.0.1* – February 2024

* Addressed https://github.com/gbif/ipt/milestone/52?closed=1[12 issues].
* Translated into 7 languages

This minor release addresses issues with inferred metadata, missing resources, and Excel source files.


== *3.0.0* – February 2024

* Addressed https://github.com/gbif/ipt/milestone/38?closed=1[141 issues].
* Translated into 7 languages

Version 3.0.0 is a major version release as it brings in a new capability that goes beyond the Darwin Core Archive format. The IPT 3 will still provide all the functions of previous versions, but will additionally allow a user to map datasets to supported https://frictionlessdata.io[Frictionless Data] schemas. The first of these is the https://tdwg.github.io/camtrap-dp/[Camera Trap Data Package (Camtrap DP)].


== *2.7.7* – November 2023

* Addressed https://github.com/gbif/ipt/milestone/50?closed=1[10 issues].
* Translated into 7 languages

This minor release addresses issues with maps and resources visibility. It also allows configuration of the default language.

== *2.7.6* – September 2023

* Addressed https://github.com/gbif/ipt/milestone/49?closed=1[13 issues].
* Translated into 7 languages

This minor release addresses issues with metadata inferring and vocabulary management.

== *2.7.5* – August 2023

* Addressed https://github.com/gbif/ipt/milestone/47?closed=1[18 issues].
* Translated into 7 languages

This minor release brings default network for IPT feature and bug fixes.


== *2.7.4* – July 2023

* Addressed https://github.com/gbif/ipt/milestone/46?closed=1[21 issues].
* Translated into 7 languages

This release brings new file uploader, new IPT setup, compressed URL sources and more.


== *2.7.3* – March 2023

* Addressed https://github.com/gbif/ipt/milestone/45?closed=1[5 issues].
* Translated into 7 languages

This minor release brings UI improvements and minor fixes.

== *2.7.2* – February 2023

* Addressed https://github.com/gbif/ipt/milestone/44?closed=1[1 issue].
* Translated into 7 languages

This minor release addresses the bug with translations.

== *2.7.1* – January 2023

* Addressed https://github.com/gbif/ipt/milestone/43?closed=1[2 issues].
* Translated into 7 languages

This minor release brings bug fixes for issue with resource tables and with DOI management.

== *2.7.0* – January 2023

* Addressed https://github.com/gbif/ipt/milestone/42?closed=1[47 issues].
* Translated into 7 languages

This major release brings many new features, bug fixes, improvements. Most important ones: new resource tables with better performance for large amount of resources; performance improvements for registration/publication process; drag-n-drop for metadata components and many more.

== *2.6.3* – October 2022

* Addressed https://github.com/gbif/ipt/milestone/41?closed=1[12 issues].
* Translated into 7 languages

This release includes security and bug fixes.

== *2.6.2* – October 2022

* Addressed https://github.com/gbif/ipt/milestone/40?closed=1[7 issues].
* Translated into 7 languages

This release includes a bug fix for user creation.

== *2.6.1* – September 2022

* Addressed https://github.com/gbif/ipt/milestone/39?closed=1[1 issue].
* Translated into 7 languages

This release includes a bug fix for empty resource tables.

== *2.6.0* – September 2022

* Addressed https://github.com/gbif/ipt/milestone/37?closed=1[42 issues].
* Translated into 7 languages

This release brings many new features, bug fixes and improvements. Namely, admin UI management (color scheme, logo upload), automatic metadata inferring and more. For details please visit https://github.com/gbif/ipt/milestone/37?closed=1[GitHub].

== *2.5.8* – May 2022

* Addressed https://github.com/gbif/ipt/milestone/35?closed=1[9 issues].
* Translated into 7 languages

This release includes a bug fix for publishing resources with DOI and other minor fixes (see https://github.com/gbif/ipt/milestone/35?closed=1[issues]).

== *2.5.7* – February 2022

* Addressed https://github.com/gbif/ipt/milestone/34?closed=1[5 issues].
* Translated into 7 languages

This release includes small user interface improvements, fixes a bug with database data sources and corrects a problem when deleting which have been assigned a DOI within the IPT. It also fixes the "Reset Password" button on the admin page.

== *2.5.6* – February 2022

* Addressed https://github.com/gbif/ipt/milestone/33?closed=1[21 issues].
* Translated into 7 languages

This version brings new Darwin Core terms (establishmentMeans, degreeOfEstablishment, pathway etc.) It also changes the way user passwords are stored to improve their security. All users are encouraged to upgrade to this version.

== *2.5.5* – December 2021

* Addressed https://github.com/gbif/ipt/milestone/32?closed=1[3 issues].
* Translated into 7 languages

This version contains further security updates to Log4J library. This also contains a fix related to the Darwin Core (identifiedByID/recordedByID terms not displayed). All users are encouraged to upgrade to this version, especially if they use those Darwin Core terms.

== *2.5.4* – December 2021

* Addressed https://github.com/gbif/ipt/milestone/31?closed=1[3 issues].
* Translated into 7 languages

This version contains fixes to critical security issues with the Struts and https://nvd.nist.gov/vuln/detail/CVE-2021-44228[Log4J] libraries. All users are highly encouraged to upgrade to this version as soon as possible.

== *2.5.3* – December 2021

* Addressed https://github.com/gbif/ipt/milestone/30?closed=1[2 issues].
* Translated into 7 languages

This version contains an update to the Spanish translation of the user interface, and a minor bugfix for the vocabularies page in the administration section. There are no other changes since version 2.5.2, and no need to upgrade if you do not wish to do so. Thanks to the work of the translators, the translation of this user manual into Spanish has been completed.

== *2.5.2* – November 2021

* Addressed https://github.com/gbif/ipt/milestone/29?closed=1[26 issues].
* Translated into 7 languages

此版本處理自 2.5 版始發現的臭蟲，主要在詮釋資料編輯及引用條目的相關功能。其它改善包括部署及系統管理，還有使用者介面及相依的新版函式庫。

== *2.5.1* – September 2021

* Addressed https://github.com/gbif/ipt/milestone/28?closed=1[4 issues].
* Translated into 7 languages

This version addresses a bug introduced in version 2.5.0, which prevented the IPT from connecting to database sources. Users who connect the IPT to database sources will need to upgrade to 2.5.1.

== *2.5.0* – August 2021

* Addressed https://github.com/gbif/ipt/milestone/27?closed=1[81 issues].
* Translated into 7 languages

This version addresses 81 issues, including the famous "double log in bug", and brings in a fresher-looking user interface. This user manual has also been refreshed, enabling a complete translation into Spanish.

== *2.4.2* – September 2020

* Addressed https://github.com/gbif/ipt/milestone/9?closed=1[1 issue].
* Translated into 7 languages

Version 2.4.2 fixes a minor security vulnerability in Apache Struts, which the IPT uses. Users should plan to upgrade to this version following the instructions in the release notes. An improvement to memory use when large datasets are read from a PostgreSQL server is also included.

== *2.4.1* – September 2020

* Addressed https://github.com/gbif/ipt/milestone/25?closed=1[12 issues].
* Translated into 7 languages

Version 2.4.1 fixes a security vulnerability in Apache Struts, which the IPT uses. Users should plan to upgrade to this version following the instructions in the release notes.

== *2.4.0* – July 2019

* Addressed https://github.com/gbif/ipt/milestone/8?closed=1[19 issues].
* Translated into 7 languages

Version 2.4.0 fixes security vulnerabilities in Apache Jackson and Apache Struts, which the IPT uses. Users should plan to upgrade to this version following the instructions in the release notes. It also updates the integration for custom DOIs from DataCite, and removes (unused) support for DOIs from EZID. The version number has been updated to 2.4.0 to reflect the removal of support for EZID.

== *2.3.6* – July 2018

* Addressed https://github.com/gbif/ipt/milestone/7?closed=1[20 issues].
* Translated into 7 languages

Version 2.3.6 fixes a security vulnerability in JQuery, which the IPT uses. Users should plan to upgrade to this version following the instructions in the release notes.

https://github.com/gbif/ipt/issues/1411[An issue] remains with custom DOIs from DataCite. If necessary, a further release of the IPT will be made in July or August.

== *2.3.5* – October 2017

* Addressed https://github.com/gbif/ipt/milestone/6[27 issues]: 6 Defects, 7 Enhancements and 15 Other
* Translated into 7 languages

Version 2.3.4 fixes a https://struts.apache.org/docs/s2-045.html[security vulnerability] that was discovered in the Apache Struts web framework, which the IPT uses. This security vulnerability affects all IPT versions, including 2.3.3, therefore all users should plan to upgrade to this version immediately following the instructions in the release notes.

== *2.3.4* – March 2017

* Addressed https://github.com/gbif/ipt/milestone/5[5 issues]: 3 Defects, 1 Enhancement and 1 Other
* Translated into 7 languages

Version 2.3.4 fixes a https://struts.apache.org/docs/s2-045.html[security vulnerability] that was discovered in the Apache Struts web framework, which the IPT uses. This security vulnerability affects all IPT versions, including 2.3.3, therefore all users should plan to upgrade to this version immediately following the instructions in the release notes.

== *2.3.3* – December 2016

* Addressed https://github.com/gbif/ipt/milestone/3[90 issues]: 22 Defects, 17 Enhancements, 36 Won’t fix, 10 Duplicates, and 5 Other
* Translated into 7 languages

A description of the exciting new features added to the IPT in version 2.3.3 are described in https://gbif.blogspot.com/2017/01/ipt-v233-your-repository-for.html[this blog post]. Additionally, please note that GBIF recently released a new set of Microsoft Excel templates for uploading data to the IPT. The new templates provide a simpler solution for capturing, formatting and uploading three types of GBIF data classes: xref:sampling-event-data.adoc[sampling-event data], xref:occurrence-data.adoc[occurrence data], and xref:checklist-data.adoc[checklist data]. More information about these templates can be found in https://www.gbif.org/newsroom/news/new-darwin-core-spreadsheet-templates[this news article].

== *2.3.2* – October 2015

* Addressed https://github.com/gbif/ipt/milestone/2?closed=1[14 issues]: 12 Defects, 2 Won’t fix
* Translated into 6 languages

== *2.3.1* – September 2015

* Addressed https://github.com/gbif/ipt/milestone/1?closed=1[3 issues]: 3 Defects
* Translated into 6 languages

== *2.3* – September 2015

* Addressed https://github.com/gbif/ipt/milestone/20?closed=1[38 issues]: 15 Defects, 15 Enhancements, 4 Won’t fix, and 4 that were considered as Tasks
* Translated into 6 languages

== *2.2.1* – April 2015

* Addressed https://github.com/gbif/ipt/milestone/19?closed=1[5 issues]: 3 Defects, 1 Enhancement, 1 Other
* Translated into 6 languages

== *2.2* – March 2015

* https://gbif.blogspot.com/2015/03/ipt-v22.html[Release Announcement]
* Addressed https://github.com/gbif/ipt/milestone/18?closed=1[74 issues]: 20 Defects, 26 Enhancements, 16 Won’t fix, 6 Duplicates, 2 Other, 1 Task, and 3 that were considered as Invalid
* Translated into 6 languages

== *2.1* – April 2014

* https://gbif.blogspot.com/2014/04/ipt-v21.html[Release Announcement]
* Addressed https://github.com/gbif/ipt/milestone/16?closed=1[85 issues]: 38 Defects, 11 Enhancements, 18 Won’t fix, 6 Duplicates, 1 Other, and 11 that were considered as Invalid
* Translated into 6 languages (Japanese translation added)

== *2.0.5* – May 2013

* https://gbif.blogspot.com/2013/05/ipt-v205-released-melhor-versao-ate-o.html[Release Announcement]
* Addressed https://github.com/gbif/ipt/milestone/14?closed=1[45 issues]: 15 Defects, 17 Enhancements, 2 Patches, 7 Won’t fix, 3 Duplicates, and 1 that was considered as Invalid
* Translated into 5 languages (Portuguese translation added)

== *2.0.4* – October 2012

* https://gbif.blogspot.com/2012/10/ipt-v204-released.html[Release Announcement]
* Addressed https://github.com/gbif/ipt/milestone/13?closed=1[108 issues]: 38 Defects, 35 Enhancements, 7 Other, 5 Patches, 18 Won't fix, 4 Duplicates, and 1 that was considered as Invalid
* Translated into 4 languages (Traditional Chinese translation added)

== *2.0.3* – November 2011

* https://gbif.blogspot.com/2011/11/important-quality-boost-for-gbif-data.html[Release Announcement]
* Addressed https://github.com/gbif/ipt/milestone/12?closed=1[85 issues]: 43 defects, 31 enhancements, 3 Patches, 7 Won’t fix, and 1 Duplicate
* Translated into 3 languages (French and Spanish translations added)

== *2.0.2* – June 2011

* https://lists.gbif.org/pipermail/ipt/2011-June/000352.html[Release Announcement]

== *2.0.1* – February 2011

* First IPT version 2 release
* https://lists.gbif.org/pipermail/ipt/2011-February/000309.html[Release Announcement]
