= Resources

== Darwin Core Archive documentation
Details about the structure of a Darwin Core Archive, abbreviated DwC-A, can be found in the "Text Guide" section of the Darwin Core web site: http://rs.tdwg.org/dwc/terms/guides/text/. Further information about the IPT's use of DwC-A can be found on xref:darwin-core.adoc[this] page.

== GBIF Help Desk
Send email messages to helpdesk@gbif.org to report problems with GBIF services, such as the GBIF Registry. Do not send IPT-specific help question to the Help Desk. Instead send them to the IPT mailing list (see below).

== GBIF Registry
Use this online application to find information about organizations, IPT instances, and resources registered with GBIF: https://www.gbif.org/dataset.

== IPT GitHub site
The https://github.org/gbif/ipt[IPT GitHub site] is the project repository for all of the open source code, management, and documentation of the IPT.

== IPT developer documentation
Developers who wish to contribute, or to use the latest revision of the source code for their installation should consult the xref:developer-guide.adoc[Developer Guide] section.

== IPT issue tracker
The https://github.com/gbif/ipt/issues[issue tracker] is the bug report and feature request management system for the IPT software and documentation.

== IPT mailing list
All *IPT Administrators* should sign up to the https://lists.gbif.org/mailman/listinfo/ipt/[IPT Mailing List] to be notified of new releases and best practices for maintaining their IPT. Have a question about how to maintain the IPT that you can't find the answer to in the xref:faq.adoc[FAQ] or xref:index.adoc[User Manual]? Then send your question to the list to get it answered!

The https://lists.gbif.org/mailman/listinfo/ipt/[IPT Mailing List] can also be used by *IPT users* to support each other. Have a question about how to use the IPT that you can't find the answer to in the xref:faq.adoc[FAQ] or xref:index.adoc[User Manual]? Then send your question to the list to get it answered!

== IPT test installation
GBIF provides a functional installation of the IPT for evaluation and testing purposes. The test installation of the latest release can be found at https://ipt.gbif.org/.
