= GBIF 統合バブリッシングツールキット（IPT） ユーザーマニュアル

_ダウンロードを含む最新版の情報は、xref:releases.adoc[リリース]ページをご覧ください。_

GBIF統合パブリッシングツールキット（IPT）は、4種類の生物多様性関連情報を簡単に共有できる、自由に利用可能なオープンソースWebアプリケーションです。

. 主要な分類群のオカレンスデータ
. 分類群チェックリスト
. サンプリングイベントデータ
. データソース全般のメタデータ

IPTインスタンスおよびIPTで登録されたデータやメタデータはGBIFレジストリに接続され、GBIFネットワークやポータルを通じて参照できるようインデックス化され、一般に利用できるようになります。また、IPTにDataCiteアカウントを設定することで、データセットにDOIを付与し、データリポジトリとして活用することも可能です。

2001年に各国政府が出資して設立されたGBIF（The Global Biodiversity Information Facility）は、インターネットを通じて生物多様性データを自由に入手できるようにするための世界最大の多国間イニシアチブです。link:https://www.gbif.org/participation/participant-list[GBIFのさまざまな参加者]は、主に国や国際機関です。GBIFは、関連する国際条約機関とも正式なパートナーシップを結んでいます。GBIFの使命は、科学、保全、持続可能な開発を支えるために、インターネットを介した生物多様性データへの自由でオープンなアクセスを世界中に促進し、可能にすることです。GBIFの詳細については、link:https://www.gbif.org/[GBIF.org]をご覧ください。

GBIFがIPTの開発を主導するようになったのは、いくつかの要因があります。

* 大規模なデータセットを容易に公開・転送するできる従来の公開ツール（DiGIR、TAPIR、BioCASe）が制限を受けたため。
* インデックス作成時に出版社のサーバーとGBIFのサーバーの両方の負荷を軽減するため。DiGIR、TAPIR、BioCASeからのインデックス作成では、HTTPリクエストとレスポンスのやりとりが繰り返され、負荷が大きくなってしまいました。
* 生物多様性データセットのインデックス作成の高速化のため。
* データ公開者にさらなるサービスやメリットを提供し、データ公開を促進するため。
* 名前チェックリストやデータセットのメタデータなど、特定の種類の生物多様性データを公開するための適切なツールがなかったため。

IPTの仕組みを理解するために、データセットがGBIF.orgを通じて適切に公開・登録される様子を25分の簡単な動画で見てみましょう。

[.responsive-video]
.IPTを利用してGBIF.orgで生物多様性データを公開する方法
video::eDH9IoTrMVE[youtube, width=100%]

== ユーザー

もしIPTを試してみたいだけなら、 helpdesk@gbif.org にメールを送ってlink:https://ipt.gbif.org/[デモIPT]のアカウントを申請してください。

IPTを使い始める最も簡単な方法は、https://www.gbif.org/data-hosting-centres[信頼できるデータホスティングセンター]に無料のアカウントを申請することです。これにより、独自のサーバでIPTをセットアップし、維持する手間をかけずに、GBIF.org を介してデータセットの管理および公開が可能となります。

また、IPTのインスタンスを自分でセットアップする場合は、xref:getting-started.adoc[はじめに]を利用してください。

NOTE: IPTユーザーのサポートグループであるlink:https://lists.gbif.org/mailman/listinfo/ipt/[IPTメーリングリスト]に必ずご登録ください。IPTを可能な限り安全かつ堅牢にするためには、IPTを最新の状態にしておくことが不可欠です。IPTの管理責任者は、すぐに更新できるよう、最新のリリースの通知を受け取るためにサインアップしておく必要があります。

== 開発者

IPTの開発はGBIFが中心となって指揮していますが、コーディングはコミュニティの努力によるもので、誰でも参加することができます。まずは、link:https://github.com/gbif/ipt/issues[未解決の問題]を見て、取り組んでみたいことを見つけてください。その貢献は、リポジトリのブランチまたはフォークを使用したlink:https://help.github.com/articles/creating-a-pull-request/[プルリクエスト]の形で歓迎されることに留意してください。開発者向けの詳しい説明は、xref:developer-guide.adoc[こちら]をご覧ください。

== 翻訳者

IPTのユーザーインターフェイスやマニュアルも国際化が必要ですが、コミュニティの活動ですので、どなたでも参加できます。翻訳者を対象とした詳細な指示は、xref:translations.adoc[こちら]で見つけることができます。

コミュニティの多大な努力と、ローカリゼーションツールlink:https://crowdin.com/project/gbif-ipt[Crowdin]の力を借りて、ユーザーインターフェースはすでに7ヶ国語（英語・フランス語・スペイン語・中国語（繁体字）・ポルトガル語（ブラジル）・日本語・ロシア語）に翻訳されています。

== 謝辞

このソフトの成功には、多くの献身的なボランティアが貢献しています。皆様のご協力により、IPTは世界中で使用される素晴らしいツールになりました。

https://crowdin.com/[Crowdin]は、このオープンソースプロジェクトを支援するため、GBIFに同社のローカリゼーション管理プラットフォームへの無償アクセスを提供しています。Crowdinは、多言語への同時翻訳の管理を可能にします。
