= 動作環境

== インターネット接続環境
IPTは、実行されるサーバーが一貫してインターネットに接続されていることを前提に設計されています。IPTの多くの機能はオフラインでも動作しますが、IPTの一部の機能（GBIF登録、拡張機能インストール、統制語彙、ソースデータ用外部データベースなど）は、外部のインターネットリソースとの通信を必要とします。IPTの管理・運用の観点からは、インターネット接続の速度はこのような通信にのみ影響します。ローカルイントラネットの外からIPTウェブアプリケーションとそのサービスにアクセスするには、常に安定した接続も必要であり、接続性の低下は、（特に大きなデータセットを転送する場合）これらの側面に悪影響を与える可能性があります。

== 安定したURL
単にlink:http://rs.tdwg.org/dwc/terms/guides/text/[ダーウィンコア・アーカイブ] を生成するツールとして使用することもできますが、IPTは発見しやすくアクセスしやすいインターネットベースのアプリケーションおよびサービスであることを意図しています。この機能をサポートするために、IPTがインストールされているサーバーは、安定したURLを介してアプリケーションとサービスへのアクセスをサポートできなければなりません。

== TLS
IPTでは必須ではありませんが、可能であれば安全なHTTPS（SSLに代わるTLS）でIPTを実行することをGBIFでは推奨しています。

== メモリ
IPTのインストールをホストするサーバーは、少なくとも256MBのRAMメモリをアプリケーションで利用できるようにする必要があります。

== ディスク容量
IPTアプリケーションに必要な容量は100MB程度です。インストール後のIPTデータ・ディレクトリの内容は、IPTによって書き込み可能な1MB未満のディスク・ストレージを必要とします。しかし、データディレクトリの内容は、リソースが作成されるにつれて大きくなり、インポートされたデータセットを含むファイルまたはテーブルのサイズとほぼ同じスペースを必要とします。比較的豊富なオカレンスデータセットの推定サイズは、1レコードあたり1キロバイトです。IPTの通常の使用では、ログファイルに情報が追加され、これは時間とともに大きくなりますが、ふつう最小限のディスクスペースのみを必要とします。

== Java バージョン

The current version of the IPT is tested to run on Java 11 and 17. Please refer to the https://adoptopenjdk.net/support.html#roadmap[OpenJDK release roadmap], the https://www.oracle.com/java/technologies/java-se-support-roadmap.html[Oracle Java version Roadmap] or documentation from your Linux distribution for an overview of how long your Java version will be supported.

OSやサーブレットコンテナのバージョンに関する注意点は、インストール手順を参照してください。

== テクニカルサポート
IPTの運用はコミットメントです。データは定期的にバックアップし、（OSやIPTの）セキュリティアップデートは、利用できるようになったらすぐに適用しなければなりません。
