= データセットのバージョン管理ポリシー

IPTはデータセットのメジャーバージョンとマイナーバージョンの変更を注意深く追跡し、公開された各バージョンを明確に識別できるようにして、ユーザーはデータセットにいつ重要な変更があったかを簡単に知ることができるようにしています。すべてのバージョン間の関係は、バージョン履歴表（ホームページ上）で見ることができ、DOIメタデータにも記録されます。

IPTが採用しているバージョン管理ポリシーは以下で説明されています。IPTのバージョン管理ポリシーは、Earth Science Information Partners（ESIP）の活動に基づくDataCiteの推奨事項に基づいていることに留意することが重要です。

== バージョン管理ポリシー

* メジャーバージョンとマイナーバージョンは、データセットの時間的な変化を追跡するために使用されます。
* バージョン番号は、major_version.minor_versionという構文で表されます。
* 新しいメジャーバージョンは、a）データセットが最初に公開されたとき、またはb）データセットに科学的に重要な変更が一つ以上加えられた後に再公開されたときに割り当てられます。何をもって科学的に重要な変更とするかは、公開者が決めなければなりません（以下の定義を参考にしてください）。
* 科学的に重要な変更とは、a）通常、データセット中の大半のレコードに影響を与え、b）そのデータセットを使った科学的分析の結果を変更しうるものです。
* 新しいメジャーバージョンは新しいDOIの作成につながりますが、新しいマイナーバージョンはそうではありません。
* 新しいマイナーバージョンは、データセットが公開されるたびに割り当てられ、これに新しいメジャーバージョンを割り当てるのは適切ではありません。
* 継続的に更新されるデータセット（時系列データセットなど） については、継続的な追加によって既存の記録に科学的に重大な変化を与えない限り、再公開のたびに新しいマイナーバージョンを割り当てることができます。この決定は公開者によってなされなければなりません。
* 前回の公開から何が変わったかについての詳しい要約は、そのデータセットの新しいメジャーバージョンやマイナーバージョンを公開する前に、公開者が入力するのが理想的です。
* データセットのメジャーバージョンとマイナーバージョンには、それぞれIPTのランディングページがあり、データセットのアーカイブバージョン（DwC-A、EML）が自由にダウンロードできるようになっています。もちろん、一般に公開されているバージョンのランディングページだけが、インターネット上で自由にアクセスできるようになります。
* すべてのIPTランディングページは、データセットを説明する包括的なメタデータレコードで構成され、データへの直接アクセスまたはアクセス方法に関する情報を提供します。
* 旧メジャーバージョンのランディングページは、旧バージョンの状態の説明とともに、新バージョン（のリンク）を示します。
* Deleted datasets have an IPT landing page that explains the dataset was removed. It the deleted dataset was assigned a DOI by the IPT, all its versions are archived otherwise its permanently deleted.
* DOIのメタデータはできるだけ豊富であるべきで、可能な限り、a）データセットの代替識別子、b）他のバージョンとの関係、c）データセットが引用している論文との関係、d）連絡先の記載があるORCIDなどを含めるべきです。
* データセットの引用には、常にバージョン番号を含めるべきであり、例えば時系列データセットを引用する際に、アクセス日時を用いる必要がなくなります。
