= Introduction

== About the GBIF Integrated Publishing Toolkit
The GBIF Integrated Publishing Toolkit (IPT) is a freely available open source web application that makes it easy to share four types of biodiversity-related information:

. primary taxon occurrence data
. taxon checklists
. sampling event data
. general metadata about data sources.

An IPT instance as well as the data and metadata registered through the IPT are connected to the GBIF Registry, are indexed for consultation via the GBIF network and portal, and are made accessible for public use. More information about the GBIF IPT can be found at the https://www.gbif.org/ipt[IPT website].

Founded and funded by governments in 2001, The Global Biodiversity Information Facility (GBIF) is the world's largest multi-lateral initiative for enabling free access to biodiversity data via the
Internet. https://www.gbif.org/participation/participant-list[GBIF's diverse Participants] include primarily countries and
international organizations. GBIF also has formal partnerships with
relevant international treaty bodies. GBIF's mission is to promote and enable free and open access to biodiversity data worldwide via the Internet to underpin science, conservation and sustainable development. More information about GBIF can be found at https://www.gbif.org/[GBIF.org].

Several factors have provided motivation for GBIF to lead the development of the IPT:

* limitations of previous publishing tools (DiGIR, TAPIR, BioCASe) to easily publish and transfer large datasets;
* the need to reduce the load on both the publisher's server, and GBIF's server during indexing. The reason being that indexing from DiGIR, TAPIR, or BioCASe caused heavy loads due to repeated HTTP request-response interactions.
* the need to speed up the process of indexing biodiversity occurrence datasets;
* the need to offer additional benefits and services to the data publishers to encourage data publication;
* the lack of appropriate tools to publish certain types of biodiversity data, such as names checklists and data set metadata.

== How to Use this Manual

This manual has three main components: an introduction with background information, a number of step-by-step tutorials and a complete reference guide including a "getting started" section and sections describing in detail the different elements of the tool.

All users are encouraged to review this introductory part and then refer to the different specific sections depending on their role(s) regarding the IPT installation. The IPT (and this manual) differentiates three type of users:

* *Administrators*: in charge of installing and configuring the IPT. They can make changes to all aspects of an instance of the IPT. Administrators should refer to the "Getting Started" and the "Administration Menu" sections of the reference guide.
* *Resource Managers*: they are able to create, edit, remove and manage resources (data sets and metadata). Depending on the settings they may have or not registration rights to publish resources through the GBIF Network. Resource managers should refer to the different tutorials depending on the type of data that they need to deal with (metadata, occurrences, special data types through extensions, etc.). The "Manage Resources Menu" section in the reference guide will also be very helpful for resource managers.
* *Basic users*: They can only browse the resources published in an IPT installation. In future releases of the IPT they will acquire further rights #OBSOLETE#. For basic users the IPT works as a simple web application so no further explanation is included in this manual.
