= Colofón

== Citación

// If English
ifeval::["{language}" == "en"]
Este manual de usuario adapta y se basa en los anteriores manuales de usuario de IPT (Réveillon 2009, Wieczorek & Braak 2016). La cita recomendada para este manual de usuario es la siguiente:
endif::[]
// Else
ifeval::["{language}" != "en"]
El link:../../../en/[manual de usuario original en inglés] se adapta y se basa en los manuales de usuario de IPT anteriores (Réveillon 2009, Wieczorek & Braak 2016). La cita recomendada para el manual del usuario en inglés es la siguiente:
// Endif
endif::[]

// English user manual citation
[quote]
Wieczorek J, Blissett M, Braak K & Podolskiy M ({localyear}) The GBIF Integrated Publishing Toolkit User Manual, version {page-component-version}. Copenhagen: GBIF Secretariat. https://ipt.gbif.org/manual/en/ipt/{page-component-version}/

// If not English
ifeval::["{language}" != "en"]
La traducción de esta versión al español es una contribución de María Alejandra Meneses Giorgi, Dairo Escobar, Ricardo Ortiz, Sara Gaviria, Camila Plata, Néstor Beltrán, Daniel Amariles y Valerie Dean del equipo Coordinador del Sistema de Información sobre Biodiversidad de Colombia (https://www.biodiversidad.co/[SiB Colombia]), la Secretaría de GBIF(https://www.gbif.org/es/publisher/fbca90e3-8aed-48b1-84e3-369afbd000ce[GBIF Secretariat]), Angela Devia del Instituto de Investigación de Recursos Biológicos Alexander Von Humboldt (http://www.humboldt.org.co/es/[IAvH]), Anabela Plos de GBIF Argentina, Emanuel Robles y Patricia Ramos de La Comisión Nacional para el Conocimiento y Uso de la Biodiversidad (https://www.gob.mx/conabio[CONABIO]), Carmen Lujano y Miguel Vega de GBIF España y el voluntario de GBIF Victor Chocho. La citación recomendada para esta traducción al español es la siguiente:

// Translated user manual citation
[quote]
Wieczorek J, Blissett M, Braak K & Podolskiy M ({localyear}) The GBIF Integrated Publishing Toolkit User Manual, version {page-component-version}. (Meneses-Giorgi MA, Escobar D, Vega M, Ramos P, Plos A, Robles-Villavicencio E, Beltrán N, Ortiz R, Gaviria S, Chocho V, Plata C, Marentes E, Devia A, Duarte A, Lujano C, Amariles D, Ruiz-Jurado V, Trans.) Copenhagen: GBIF Secretariat. https://ipt.gbif.org/manual/{language}/ipt/{page-component-version}/
// Endif
endif::[]

== Derechos de autor

El GBIF Integrated Publishing Toolkit y este manual de usuario está protegido por Derechos de autor © 2016–{localyear} por la Secretaría del Servicio Global de Información sobre Biodiversidad.

== Licencia

El Integrated Publishing Toolkit de GBIF es un software de código abierto lanzado bajo la Licencia Apache Versión 2.0. Usted puede obtener una copia de esta Licencia en http://www.apache.org/licenses/LICENSE-2.0. A menos que lo exija la ley aplicable o se acuerde por escrito, el software distribuido bajo esta Licencia se distribuye "tal cual", sin garantías de condiciones de ningún tipo, ya sean expresas o implícitas. Vea la Licencia para lenguaje específico bajo los derechos y limitaciones que rigen en virtud de la Licencia.

Este manual de usuario se publica bajo la licencia Creative Commons Attribution 4.0 International License. Puede obtener una copia de esta licencia en https://creativecommons.org/licenses/by/4.0/.

== Referencias

// GitHub and Google Code versions
Wieczorek J & Braak K (2016) The GBIF Integrated Publishing Toolkit User Manual, version 2.3.6. Copenhagen: GBIF Secretariat. https://github.com/gbif/ipt/wiki/IPTUserManualv23.wiki

// https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/gbif-providertoolkit/GBIF_IPT_User_Manual_1.0.pdf
Réveillon A (2009) The GBIF Integrated Publishing Toolkit User Manual, version 1.0. Copenhagen: GBIF Secretariat. https://links.gbif.org/ipt_manual_1.0
