= Manual del Usuario del IPT

El Integrated Publishing Toolkit (IPT) de GBIF es una aplicación web de código abierto, disponible de forma gratuita, que facilita compartir cuatro tipos de información sobre biodiversidad:

. Datos primarios sobre registros biológicos
. Listas de chequeo taxonómico
. Datos de Eventos de muestreo
. Metadatos de conjuntos de datos

Una instancia del IPT, así como los datos y metadatos registrados a través del mismo, están conectados al Sistema Global de Descubrimiento de Recursos sobre Biodiversidad (GBRDS, conocido también como el Registro GBIF), indexados por consulta a través de la red y el portal GBIF, y disponibles para uso público.  The IPT can also be configured with a DataCite account in order to assign DOIs to datasets transforming it into a data repository.  Puede encontrar más información sobre el IPT de GBIF en el https://www.gbif.org/ipt[sitio web de IPT].

Fundada y financiada por los gobiernos en el año 2001, la Infraestructura Mundial de Información en Biodiversidad (GBIF) es la iniciativa multilateral más grande del mundo, creada para facilitar el acceso libre a datos sobre biodiversidad a través de Internet. Entre los diversos https://www.gbif.org/participation/participant-list[Aliados de GBIF] se incluyen principalmente países y organizaciones internacionales. GBIF también ha constituido alianzas formales con importantes organismos que son producto de tratados internacionales. La misión de GBIF consiste en promover y facilitar el acceso libre y gratuito a datos sobre biodiversidad en todo el mundo, a través de Internet, para apoyar a la ciencia, la conservación y el desarrollo sostenible. Puede obtener más información acerca de GBIF en https://www.gbif.org/[GBIF.org].

Múltiples factores han servido como motivación para que GBIF lidere el desarrollo del IPT:

* Las limitaciones de aplicaciones y protocolos anteriores (DiGIR, TAPIR, ABCD) para publicar y transferir fácilmente conjuntos de datos de gran tamaño;
* La necesidad de reducir la carga en los servidores de los publicadores y de GBIF durante el proceso de indexación. Esto se debe a que el proceso de indexación desde DiGIR, TAPIR, o BioCASE se convierte en una carga pesada debido a las interacciones requerimiento-respuesta HTTP repetidas;
* La necesidad de agilizar el proceso de indexación de los conjuntos de datos sobre biodiversidad;
* La necesidad de ofrecer beneficios y servicios adicionales a los publicadores de datos para incentivar la publicación;
* La carencia de herramientas apropiadas para la publicación de determinado tipo de datos sobre biodiversidad, tales como nombres, listas de chequeo y metadatos.

To understand how the IPT works, try watching this concise 25 minute live demo showing how a dataset gets properly published and registered through GBIF.org.

.How to publish biodiversity data through GBIF.org using the IPT
video::eDH9IoTrMVE[youtube,width=100%]

== Users

If you're only interested in trying out the IPT please request an account on the https://ipt.gbif.org/[Demo IPT] by sending an email to helpdesk@gbif.org.

The simplest way to begin using the IPT is to request a free account on a xref:data-hosting-centres.adoc[trusted data hosting centre] allowing you to manage your own datasets and publish them through GBIF.org without the hassle of setting up and maintaining the IPT on your own server.

Otherwise if want to setup your own instance of the IPT the xref:getting-started.adoc[Getting Started Guide] is your entry point.

NOTE: Be sure to sign up to the https://lists.gbif.org/mailman/listinfo/ipt/[IPT Mailing List], which serves as a support group for IPT users. It is essential that the IPT is kept up to date to be as secure and robust as possible, so if you are responsible for administering an IPT, then you should be signed up to be notified of new releases so that you can update immediately.

== Developers

The core development of the IPT is directed by GBIF, but the coding is a community effort and everyone is welcome to join. Start by browsing the https://github.com/gbif/ipt/issues[Open Issues] to find something that you'd like to start working on. Kindly note that contributions are welcome in the form of a https://help.github.com/articles/creating-a-pull-request/[pull request] using a branch or fork of the repository. Full instructions aimed at developers can be found xref:developer-guide.adoc[here].

== Translators

The IPT user interface and manual both need internationalization, but it's a community effort and everyone is welcome to join. Full instructions aimed at translators can be found xref:translations.adoc[here].

Thanks to an enormous community effort, and by leveraging the power of the https://crowdin.com/project/gbif-ipt[Crowdin] localization tool, the user interface has already been translated into seven different languages: English, French, Spanish, Traditional Chinese, Brazilian Portuguese, Japanese, and Russian.

== Acknowledgements

A large number of dedicated volunteers contribute to the success of this software. With your help, the IPT has become a successful tool in use all around the world.

https://crowdin.com/[Crowdin] is kindly supporting this open source project by giving GBIF a free access to its localization management platform. Crowdin makes it possible to manage a large number of concurrent translations.
