= ¿Cómo usar este manual?

Este manual consta de tres componentes principales: una introducción con información de contexto, una serie de tutoriales y una completa guía de referencia, incluyendo la sección "Guía de Instalación" y unas secciones que describen detalladamente los diferentes elementos de la herramienta.

Se invita a todos los usuarios a revisar esta sección introductoria y a que posteriormente, dependiendo del papel que cumplan en la instalación del IPT, se dirijan a las secciones específicas. El IPT (y este manual) distingue tres tipos de usuarios:

* *Administrators*: in charge of installing and configuring the IPT. They can make changes to all aspects of an instance of the IPT. Administrators should refer to the xref:getting-started.adoc[Getting Started] and xref:administration.adoc[Administration Menu] sections of the reference guide.
* *Resource Managers*: they are able to create, edit, remove and manage resources (data sets and metadata). Depending on the settings they may or may not have registration rights to publish resources through the GBIF Network. Resource managers should refer to the different xref:how-to-publish.adoc[tutorials] depending on the type of data that they need to deal with (xref:resource-metadata.adoc[metadata], xref:occurrence-data.adoc[occurrences], special data types through extensions, etc.). The xref:manage-resources.adoc[Manage Resources Menu] section will also be very helpful for resource managers.
* *Usuarios básicos*: Sólo podrán navegar a través de los recursos publicados en una instalación del IPT. En futuras versiones del IPT, estos usuarios adquirirán derechos adicionales. Para los usuarios básicos, el IPT funcionará como una aplicación web sencilla, de manera que no se incluirá una explicación más detallada en este manual.
