= Notas de la versión

*Versiones IPT: pass:[2.5.*]*

include::partial$version-outdated.adoc[]

== Instrucciones de actualización

WARNING: Asegúrese de *realizar una copia de seguridad del directorio de datos del IPT antes de ejecutar una actualización*. Según los xref:data-hosting-centres.adoc#data-hosting-centre-criteria[Criterios de los centros de alojamiento de datos], se recomienda encarecidamente realizar copias de seguridad programadas para los directorios de datos del IPT en general. 

CAUTION: Una vez que un IPT ha sido actualizado a la versión 2.5.6 o posterior desde la 2.5.5 o anterior, no será posiblecambiar a una versión anterior debido a los cambios en los archivos de configuración del IPT.

Verifique que su sistema cumple con los xref:requirements.adoc[requisitos de instalación] para esta versión. Asegúrese que su sistema operativo y cualquier otro software instalado (como Java, Tomcat y Apache HTTPD) están actualizados con los parches de seguridad.

El método de actualización depende del xref:installation.adoc#installation-method[método de instalación] original.

=== Actualizaciones utilizando paquetes Linux

Los usuarios de paquetes Linux en Red Hat, CentOS, Debian, Ubuntu, etc. pueden realizar la actualización utilizando el gestor de paquetes del sistema.

[source, shell]
----
# Red Hat, CentOS etc:
yum update ipt
# Debian, Ubuntu etc:
apt install ipt
----

Estos comandos se pueden usar para probar una versión anterior en Red Hat/CentOS:

[source, shell]
----
# Asegurarse de que la configuración del repositorio GBIF está actualizada:
yum-config-manager --add-repo https://packages.gbif.org/gbif.repo

# Instalar la última versión testada:
yum install --enablerepo=gbif-testing ipt

# Volver a una versión anterior estable:
yum downgrade ipt-2.4.2

# Mostrar todas las versiones disponibles, testadas y estables:
yum --showduplicates list --enablerepo=gbif-testing ipt
----


=== Actualizaciones utilizando un contenedor de servlet

TIP: Al actualizar a la versión 2.5.0 o posterior, siga el xref:installation.adoc#tomcat[paso 2] de las instrucciones de instalación para establecer una ubicación de directorio de datos. Ya no tendrá que reconfigurar el directorio de datos cada vez que actualice el IPT.

Una actualización se puede ejecutar en 4 pasos:

. Realice una copia de seguridad del directorio de datos existente y de cualquier xref:customization.adoc[estilo personalizado] (imágenes, hojas de estilo, etc.) antes de actualizar su IPT.
. Without shutting down Tomcat, replace the previous .war file with the latest edition, but keep the same name (e.g. `ipt.war`).
+
NOTE: Si reemplaza el archivo .war mientras Tomcat está apagado, asegúrese de eliminar el directorio expandido asociado antes de reiniciar Tomcat, para que el archivo WAR actualizado aparezca expandido de nuevo cuando inicie Tomcat.

. (Si el directorio de datos no está configurado con Tomcat). Abra inmediatamente el IPT en un buscador web y reutilice el directorio de datos existente en la página de opciones del IPT inicial
. Para asegurarse de que la actualización funcione, intente iniciar sesión busque el número de la nueva versión en el pie de página. (_Reinicie Tomcat si aún aparece la versión anterior._)
. Vuelva a aplicar su estilo personalizado (si aplica)

=== Actualizaciones utilizando Docker

Vea las instrucciones de xref:installation.adoc#installation-using-docker[instalación utilizando Docker]. En general, la etiqueta `latest` apuntará a la versión actual estable.

== Instrucciones para después de la actualización

Tras la actualización, puede aparecer un mensaje de advertencia indicando que algunos recursos no se han podido cargar. Esto sucede cuando a un recurso antiguo le faltan los metadatos necesarios después de que no se ha vuelto a publicar luego mucho tiempo. Los gestores de recursos pueden solucionar este problema volviendo a publicar los recursos afectados.

Una novedad en el IPT 2.3.x es la capacidad para publicar datos basados en muestras. Una vez que la actualización se ha completado, el administrador del IPT debe instalar el núcleo de Eventos Darwin Core. Tenga en cuenta que el núcleo de Eventos Darwin Core está instalado por defecto en las instalaciones nuevas.

Adicionalmente, el administrador del IPT debería actualizar todos los ficheros centrales y extensiones a sus últimas versiones. Esto permitirá a los publicadores aprovechar los nuevos términos y vocabularios incluidos en las últimas versiones.

== Cambios importantes en esta versión

La lista completa de características nuevas está documentada en la xref:releases.adoc[página de la versión]. Por favor, preste especial atención a estos puntos después de actualizar: 

* IPT 2.5.6 cambia la manera en que se almacenan las contraseñas de usuarios para mejorar la seguridad. Cuando el IPT ha sido actualizado a la versión 2.5.6 (o posterior), no es posible regresar a una versión anterior.
* IPT 2.5.2 incluye una corrección de errores en la edición de metadatos. Utilice esta versión en vez de la 2.5.0 o la 2.5.1.
* IPT 2.5.1 incluye una corrección de errores para conectarse a las fuentes de la base de datos, pero por lo demás es idéntica a la versión 2.5.0.
* El IPT 2.5.0 incluye concectores de bases de datos (bibliotecas JDBC) actualizados para MySQL, PostgreSQL, MS SQL Server, Sybase y Oracle. Por favor, compruebe que las configuraciones de su base de datos aún funciona.
* IPT 2.5.0 ahora incluye una página de solución de problemas, con todos los detalles accesibles sólo para los administradores desde el menú principal.
* El IPT 2.5.0 puede ahora leer una ubicación de directorio de datos desde un contenedor servlet, vea el xref:installation.adoc#tomcat[paso 2] de las instrucciones de instalación.
* El IPT 2.5.0 ya no es compatible con Microsoft Internet Explorer. (El propio Microsoft https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/[ya no es compatible con MSIE] para sus servidores online MS365.)
* La documentación se ha movido a esta nueva ubicación; se aportarán enlaces desde la antigua Wiki de GitHub.

Si está actualizando desde una versión anterior a la 2.4, por favor, consulte las notas de la link:../../../en/ipt/2.4/release-notes[versión antigua].

== Cuando todo lo demás falla

Explore las xref:faq.adoc[preguntas frecuentes], que continúan siendo actualizadas con buenas preguntas o pregunte en la https://lists.gbif.org/mailman/listinfo/ipt/[lista de mailing del IPT].
